---
# SPDX-FileCopyrightText: 2024 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

baseURL: 'https://ohwr.org/'
title: 'Open Hardware Repository'
summaryLength: 30
outputs:
  home:
    - 'html'
    - 'SearchIndex'
markup:
  highlight:
    codeFences: true
    noClasses: true
    style: 'native'
taxonomies:
  category: 'categories'
  newsfeed: 'newsfeeds'
module:
  imports:
    - path: 'github.com/OHWR/bigspring-light-hugo'
menus:
  main:
    - name: 'About'
      url: 'about/'
      weight: 1
    - name: 'Projects'
      url: 'projects/'
      weight: 2
    - name: 'Categories'
      url: 'categories/'
      weight: 3
    - name: 'Licenses'
      url: 'licenses/'
      weight: 4
    - name: 'Forum'
      url: 'https://forums.ohwr.org/'
      weight: 5
    - name: 'News'
      url: 'news/'
      weight: 6
  footer_left:
    - name: 'About'
      url: 'about/'
    - name: 'Projects'
      url: 'projects/'
  footer_middle:
    - name: 'Licenses'
      url: 'licenses/'
    - name: 'Forum'
      url: 'https://forums.ohwr.org/'
  footer_right:
    - name: 'News'
      url: 'news/'
    - name: 'Submit Project'
      url: 'submit-project/'
params:
  favicon: 'https://be-cem-edl.web.cern.ch/ohwr/graphics/favicon.ico'
  logo: 'https://be-cem-edl.web.cern.ch/ohwr/graphics/logo.png'
  logo_width: '325px'
  variables:
    text_color: '#022b3a'
    text_color_dark: '#022b3a'
    primary_color: '#fd810d'
    light: '#f5faf6'
  navigation_button:
    enable: true
    label: 'Submit Project'
    link: 'submit-project/'
  search:
    primary_color: '#fd810d'
