---
# SPDX-FileCopyrightText: 2025 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

name: REUSE Compliance Check

on: [push, pull_request, workflow_dispatch]  # yamllint disable-line rule:truthy

jobs:
  reuse-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5
